### ISSUE TITLE
load translated data by default

### ISSUE THREAD

**Issue by ainilaha** [cran/nhanesA#3]
Hi Chris

Could you update `nhanes(nh_table, includelabels = FALSE)` to `nhanes(nh_table, includelabels = FALSE, translated = TRUE)` by adding `translated = TRUE` parameter?  In the docker version, the function loads the translated data unless the users explicitly want to load the raw data by set `translated = FALSE`.
For example,
`nhanes("DEMO_C")` # By default, it would be better if it loads the categorical variables such as gender (`RIAGENDR`) column should fill with `Male` and `Female`  instead of the integer numbers.

Thanks,
Laha

**Comment by cjendres1** [comment]
Hi Laha, 
I don't receive messages from this repo cause it is owned by CRAN.
Also, this CRAN mirror repo is not used for code development.

Please close this issue and post to my repository: https://github.com/cjendres1/nhanes/issues
